#!/bin/sh
#shellcheck shell=sh
set -eu

SCRIPTDIR="$(dirname "$(realpath "$0")")"

main() {
  clang-format -i --style=Chromium "$SCRIPTDIR"/*.c >/dev/null 2>&1
  nixfmt "$SCRIPTDIR"/*.nix
  zig fmt "$SCRIPTDIR"/*.zig

  printf \\033\[1\;32m%s\\033\[0m\\n "zig build"
  zig build
  printf \\n\\033\[1\;32m%s\\033\[0m\\n "nix build"
  nix build --print-build-logs

  for i in $(fd -aL . "$SCRIPTDIR/result" ); do
    printf \\n
    nix run "nixpkgs#file" -- "$i" | sed -E 's@/nix/store/[^/]+/@@g'
    du -h "$i" | cut -f1
    $i
    printf \\n
  done
}

main
