#!/bin/sh
# shellcheck shell=sh

repository_root="$(dirname "$(realpath "$0")")"
cd "$repository_root" || fail "Error: cannot cd into $repository_root"

set -eu

fail() {
  printf \\033\[0\;31m%s\\033\[0m\\n "$*" > /dev/stderr
  exit 1
}

if test -d ./out
then
  rm -f ./out/*
else
  mkdir -p ./out
fi

out="$(nix build .^out --print-out-paths --no-link --print-build-logs)"
# shellcheck disable=SC2086
cp -vL $out/* ./out
